-- Using mediumint when dealing with 32-bit flags... Smart.
ALTER TABLE `smart_scripts` MODIFY COLUMN `event_param1` INT(11) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `smart_scripts` MODIFY COLUMN `event_param2` INT(11) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `smart_scripts` MODIFY COLUMN `event_param3` INT(11) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `smart_scripts` MODIFY COLUMN `event_param4` INT(11) UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE `smart_scripts` MODIFY COLUMN `action_param1` INT(11) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `smart_scripts` MODIFY COLUMN `action_param2` INT(11) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `smart_scripts` MODIFY COLUMN `action_param3` INT(11) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `smart_scripts` MODIFY COLUMN `action_param4` INT(11) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `smart_scripts` MODIFY COLUMN `action_param5` INT(11) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `smart_scripts` MODIFY COLUMN `action_param6` INT(11) UNSIGNED NOT NULL DEFAULT 0;
