-- world

CREATE TABLE item_extended_cost
(
id INT UNSIGNED NOT NULL,
honor INT UNSIGNED NOT NULL DEFAULT 0,
arena INT UNSIGNED NOT NULL DEFAULT 0,
item0 INT UNSIGNED NOT NULL DEFAULT 0,
item_count0 INT UNSIGNED NOT NULL DEFAULT 0,
item1 INT UNSIGNED NOT NULL DEFAULT 0,
item_count1 INT UNSIGNED NOT NULL DEFAULT 0,
item2 INT UNSIGNED NOT NULL DEFAULT 0,
item_count2 INT UNSIGNED NOT NULL DEFAULT 0,
item3 INT UNSIGNED NOT NULL DEFAULT 0,
item_count3 INT UNSIGNED NOT NULL DEFAULT 0,
item4 INT UNSIGNED NOT NULL DEFAULT 0,
item_count4 INT UNSIGNED NOT NULL DEFAULT 0,
req_rating INT UNSIGNED NOT NULL DEFAULT 0,
PRIMARY KEY (id)
);
