-- world

CREATE TABLE loot_zone_drops
(
zone_id INT UNSIGNED NOT NULL DEFAULT 0,
item_id INT UNSIGNED NOT NULL DEFAULT 0,
chance FLOAT NOT NULL DEFAULT 100,
min_count TINYINT UNSIGNED NOT NULL DEFAULT 1,
max_count TINYINT UNSIGNED NOT NULL DEFAULT 1,
exclusion_list TEXT DEFAULT NULL,
PRIMARY KEY (zone_id, item_id)
);
