CREATE TABLE `spell_dbc` (
    `Id` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `Category` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `Dispel` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `Mechanic` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `Attributes` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `AttributesEx` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `AttributesEx2` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `AttributesEx3` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `AttributesEx4` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `AttributesEx5` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `AttributesEx6` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `Stances` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `StancesNot` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `Targets` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `TargetCreatureType` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `RequiresSpellFocus` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `FacingCasterFlags` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `CasterAuraState` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `TargetAuraState` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `CasterAuraStateNot` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `TargetAuraStateNot` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `CastingTimeIndex` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `RecoveryTime` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `CategoryRecoveryTime` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `InterruptFlags` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `AuraInterruptFlags` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `ChannelInterruptFlags` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `procFlags` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `procChance` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `procCharges` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `maxLevel` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `baseLevel` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `spellLevel` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `DurationIndex` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `powerType` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `manaCost` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `manaCostPerlevel` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `manaPerSecond` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `manaPerSecondPerLevel` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `rangeIndex` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `speed` float NOT NULL DEFAULT '0',
    `StackAmount` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `Totem1` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `Totem2` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `Reagent1` int(10) NOT NULL DEFAULT '0',
    `Reagent2` int(10) NOT NULL DEFAULT '0',
    `Reagent3` int(10) NOT NULL DEFAULT '0',
    `Reagent4` int(10) NOT NULL DEFAULT '0',
    `Reagent5` int(10) NOT NULL DEFAULT '0',
    `Reagent6` int(10) NOT NULL DEFAULT '0',
    `Reagent7` int(10) NOT NULL DEFAULT '0',
    `Reagent8` int(10) NOT NULL DEFAULT '0',
    `ReagentCount1` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `ReagentCount2` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `ReagentCount3` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `ReagentCount4` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `ReagentCount5` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `ReagentCount6` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `ReagentCount7` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `ReagentCount8` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EquippedItemClass` int(10) NOT NULL DEFAULT '0',
    `EquippedItemSubClassMask` int(10) NOT NULL DEFAULT '0',
    `EquippedItemInventoryTypeMask` int(10) NOT NULL DEFAULT '0',
    `Effect1` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `Effect2` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `Effect3` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectDieSides1` int(10) NOT NULL DEFAULT '0',
    `EffectDieSides2` int(10) NOT NULL DEFAULT '0',
    `EffectDieSides3` int(10) NOT NULL DEFAULT '0',
    `EffectBaseDice1` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectBaseDice2` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectBaseDice3` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectDicePerLevel1` float NOT NULL DEFAULT '0',
    `EffectDicePerLevel2` float NOT NULL DEFAULT '0',
    `EffectDicePerLevel3` float NOT NULL DEFAULT '0',
    `EffectRealPointsPerLevel1` float NOT NULL DEFAULT '0',
    `EffectRealPointsPerLevel2` float NOT NULL DEFAULT '0',
    `EffectRealPointsPerLevel3` float NOT NULL DEFAULT '0',
    `EffectBasePoints1` int(10) NOT NULL DEFAULT '0',
    `EffectBasePoints2` int(10) NOT NULL DEFAULT '0',
    `EffectBasePoints3` int(10) NOT NULL DEFAULT '0',
    `EffectMechanic1` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectMechanic2` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectMechanic3` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectImplicitTargetA1` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectImplicitTargetA2` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectImplicitTargetA3` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectImplicitTargetB1` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectImplicitTargetB2` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectImplicitTargetB3` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectRadiusIndex1` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectRadiusIndex2` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectRadiusIndex3` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectApplyAuraName1` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectApplyAuraName2` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectApplyAuraName3` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectAmplitude1` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectAmplitude2` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectAmplitude3` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectMultipleValue1` float NOT NULL DEFAULT '0',
    `EffectMultipleValue2` float NOT NULL DEFAULT '0',
    `EffectMultipleValue3` float NOT NULL DEFAULT '0',
    `EffectChainTarget1` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectChainTarget2` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectChainTarget3` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectItemType1` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectItemType2` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectItemType3` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectMiscValue1` int(10) NOT NULL DEFAULT '0',
    `EffectMiscValue2` int(10) NOT NULL DEFAULT '0',
    `EffectMiscValue3` int(10) NOT NULL DEFAULT '0',
    `EffectMiscValueB1` int(10) NOT NULL DEFAULT '0',
    `EffectMiscValueB2` int(10) NOT NULL DEFAULT '0',
    `EffectMiscValueB3` int(10) NOT NULL DEFAULT '0',
    `EffectTriggerSpell1` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectTriggerSpell2` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectTriggerSpell3` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `EffectPointsPerComboPoint1` float NOT NULL DEFAULT '0',
    `EffectPointsPerComboPoint2` float NOT NULL DEFAULT '0',
    `EffectPointsPerComboPoint3` float NOT NULL DEFAULT '0',
    `SpellVisual` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `SpellIconID` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `activeIconID` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `SpellName1` char(128) NOT NULL DEFAULT '',
    `SpellName2` char(128) NOT NULL DEFAULT '',
    `SpellName3` char(128) NOT NULL DEFAULT '',
    `SpellName4` char(128) NOT NULL DEFAULT '',
    `SpellName5` char(128) NOT NULL DEFAULT '',
    `SpellName6` char(128) NOT NULL DEFAULT '',
    `SpellName7` char(128) NOT NULL DEFAULT '',
    `SpellName8` char(128) NOT NULL DEFAULT '',
    `SpellName9` char(128) NOT NULL DEFAULT '',
    `SpellName10` char(128) NOT NULL DEFAULT '',
    `SpellName11` char(128) NOT NULL DEFAULT '',
    `SpellName12` char(128) NOT NULL DEFAULT '',
    `SpellName13` char(128) NOT NULL DEFAULT '',
    `SpellName14` char(128) NOT NULL DEFAULT '',
    `SpellName15` char(128) NOT NULL DEFAULT '',
    `SpellName16` char(128) NOT NULL DEFAULT '',
    `Rank1` char(64) NOT NULL DEFAULT '',
    `Rank2` char(64) NOT NULL DEFAULT '',
    `Rank3` char(64) NOT NULL DEFAULT '',
    `Rank4` char(64) NOT NULL DEFAULT '',
    `Rank5` char(64) NOT NULL DEFAULT '',
    `Rank6` char(64) NOT NULL DEFAULT '',
    `Rank7` char(64) NOT NULL DEFAULT '',
    `Rank8` char(64) NOT NULL DEFAULT '',
    `Rank9` char(64) NOT NULL DEFAULT '',
    `Rank10` char(64) NOT NULL DEFAULT '',
    `Rank11` char(64) NOT NULL DEFAULT '',
    `Rank12` char(64) NOT NULL DEFAULT '',
    `Rank13` char(64) NOT NULL DEFAULT '',
    `Rank14` char(64) NOT NULL DEFAULT '',
    `Rank15` char(64) NOT NULL DEFAULT '',
    `Rank16` char(64) NOT NULL DEFAULT '',
    `ManaCostPercentage` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `StartRecoveryCategory` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `StartRecoveryTime` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `MaxTargetLevel` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `SpellFamilyName` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `SpellFamilyFlags` bigint(20) UNSIGNED NOT NULL DEFAULT '0',
    `MaxAffectedTargets` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `DmgClass` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `PreventionType` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `DmgMultiplier1` float NOT NULL DEFAULT '0',
    `DmgMultiplier2` float NOT NULL DEFAULT '0',
    `DmgMultiplier3` float NOT NULL DEFAULT '0',
    `TotemCategory1` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `TotemCategory2` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `AreaId` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `SchoolMask` int(10) UNSIGNED NOT NULL DEFAULT '0',
    PRIMARY KEY (`Id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED COMMENT='Generated from spell_dbc.txt';